import json
OUT='/Users/Flo/GitHub/palette/research/v3/phase-3/embeddings'
d=json.load(open(f'{OUT}/coverage.json'))
L=[];w=L.append
c=d['clustering']; rs=d['reviewSources']; h=d['holes']; dr=d['proposedDraw']
w('# Cluster coverage of reviewed covers, and the next round’s draw')
w('')
w('**Files:** `COVERAGE.md` (this) and `coverage.json` (machine-readable, including the per-cluster')
w('id lists and the full draw record).')
w('')
w('## The question')
w('')
w('Of the 36 clusters the corpus was cut into, which ones has the reviewer actually judged a')
w('**palette** on — and which ones has nobody ever looked at? A cluster nobody has judged is a')
w('**category hole**: a kind of cover on which no arm has ever been graded, so nothing is known')
w('about how it behaves, good or bad.')
w('')
w('## Method')
w('')
w(f"- **Clustering:** k={c['k']}, seed `{c['seedHex']}`, arm `{c['arm']}`, over the {c['universeArtworks']}-artwork")
w(f"  coverage-set universe, {c['source']}.")
w(f"  Verification: {c['verification']}.")
w('  Nothing was re-embedded and no new clustering was invented — this is the same 36 clusters')
w('  `data/coverage-set/COVERAGE_SET.md` reports, recovered so that arbitrary covers can be placed in it.')
w(f"- **Phase 3 =** batches {', '.join('`'+b+'`' for b in rs['phase3Batches'])} — **{rs['phase3DistinctCovers']} distinct covers**.")
w(f"- **Phase 2 =** every batch whose id starts `{rs['phase2BatchPrefix']}` — **{rs['phase2DistinctCovers']} distinct covers**")
w('  (48 carry a verdict; the 49th, `ab67616d00001e0200000bbc3367a621256ce593`, carries the single')
w('  `veto` record. Both count as judged.)')
w(f"- **Other batches** ({rs['otherDistinctCoversMappedToClusters']} distinct covers placed in a cluster) are reported in their own column and")
w(f"  are **not** part of the hole test. {rs['otherBatchesNote']}")
w(f"  A further {rs['otherDistinctCoversNotMappable']} covers touched by those batches cannot be placed at all: {rs['notMappableNote']}")
w('')
w('## Per-cluster coverage')
w('')
w('| cluster | universe | corpus share | Phase 2 | Phase 3 | P2+P3 | other batches | hole? |')
w('|---|---|---|---|---|---|---|---|')
for r in d['clusters']:
    w(f"| {r['cluster']} | {r['universeArtworks']} | {r['corpusSharePct']}% | {r['phase2Covers']} | {r['phase3Covers']} | {r['phase2Plus3']} | {r['otherBatchCovers']} | {'**HOLE**' if r['categoryHole'] else ''} |")
tot2=sum(r['phase2Covers'] for r in d['clusters']); tot3=sum(r['phase3Covers'] for r in d['clusters'])
w(f"| **total** | {c['universeArtworks']} | 100% | {tot2} | {tot3} | {tot2+tot3} | {rs['otherDistinctCoversMappedToClusters']} | {h['count']} holes |")
w('')
w('## The holes')
w('')
w(f"**{h['count']} of 36 clusters hold {h['corpusSharePct']}% of the corpus and have never had a palette judged on them**")
w('in Phase 2 or Phase 3, in descending corpus share:')
w('')
w('| cluster | universe | corpus share | other-batch contact |')
w('|---|---|---|---|')
byc={r['cluster']:r for r in d['clusters']}
for cl in h['clusters']:
    r=byc[cl]
    w(f"| {cl} | {r['universeArtworks']} | {r['corpusSharePct']}% | {r['otherBatchCovers']} |")
w('')
w(f"Caveat, stated so nobody over-reads the list: {h['noteOnOtherBatches']}. All ten hole clusters")
w('have had at least one cover in front of the reviewer for some *other* question (a SAM mask, a')
w('perception judgement, an accent label) — the column above shows how many. What has never')
w('happened in any of them is a palette verdict.')
w('')
w('Read the other direction: judgement so far is concentrated. Clusters 15 and 35 carry 6 judged')
w('covers each and 16 and 28 carry 4, while a quarter of the corpus carries none. Phase 2 reached')
w('25 of 36 clusters; Phase 3’s 13 covers sit in 11 clusters, so **Phase 3 alone has 25 holes**.')
w('')
w('## Proposed draw for the next round — 8 covers')
w('')
w('**Not staged, not pushed, not registered as a round.** This is a proposal; a round is a')
w('reviewer decision.')
w('')
w(f"- **Seed:** `{dr['seedHex']}` ({dr['seedDecimal']}), mulberry32 — {dr['method']}")
w(f"- **Candidate order:** {', then '.join(dr['candidateOrder'])}.")
w('- **Filters, all applied in order:**')
for f in dr['filters']:
    w(f'  - {f}')
w(f"- **Allocation:** {', '.join(f'cluster {k} → {v}' for k, v in sorted(dr['allocation'].items(), key=lambda kv: -int(kv[1])) if v)}"
  f" (clusters 11 and 31 get 0 — they are the two smallest holes at 1.22% and 1.21%).")
w(f"- **Rejections during the walk:** {len(dr['rejectionsDuringWalk'])}. Every stratum’s first shuffled candidate passed every filter.")
w('')
w('| # | cluster | cluster share | id | path | WxH | tier | drawn from |')
w('|---|---|---|---|---|---|---|---|')
for p in dr['covers']:
    w(f"| {p['slot']} | {p['cluster']} | {p['clusterCorpusSharePct']}% | `{p['id']}` | `{p['path']}` | {p['wxh']} | {p['tier']} | {p['drawnFrom']} |")
w('')
w('Every WxH above was re-read from the image header with Pillow at draw time and matched the')
w('dimensions recorded in the embedding ids file; every file was confirmed present on disk. All')
w('eight are `role: "core"` coverage-set-1 members, so all eight are in the embedding universe and')
w('carry a near-duplicate component id.')
w('')
w('Resolution mix of the eight: four at 640 px, two at 300 px, one at 700 px and one at 500 px —')
w('six of eight in the 401–640 tier against the corpus’s 61.6%, two in ≤400 against 26.5%. Close')
w('enough not to need repair, and not forced: the draw stratifies on cluster, not on tier, because')
w('the holes are the thing being closed.')
w('')
w('## What this draw does not do')
w('')
w('1. **It closes 8 of 10 holes, not all 10.** Clusters 11 and 31 (2.4% of the corpus between them)')
w('   stay dark. Adding them means a 10-cover round.')
w('2. **One cover per cluster is presence, not coverage.** After this round each of those clusters')
w('   has exactly one judged cover — enough to say the kind has been seen, nowhere near enough to')
w('   say how an arm behaves on it.')
w('3. **It carries no returning covers.** Rounds 1 and 2 both carried returning covers to measure')
w('   drift. These eight are all fresh; if drift measurement matters more than hole-closing, the')
w('   round needs to be bigger or the allocation split.')
w('4. **The near-duplicate census is a lower bound** (it undercounts by ~46% against filename ground')
w('   truth), so “never reviewed” is guaranteed only down to cosine 0.95. Same caveat as rounds 1 and 2.')
w('')
w('## Reproducing this')
w('')
w('```')
w('cd /Users/Flo/GitHub/palette')
w('V=research/v3/oracle/embeddings/.venv/bin/python')
w('T=research/v3/phase-3/embeddings/tools')
w('# 1. recover the coverage-set clustering (writes tools/clusters.json, ~5 MB, ~2 min, CPU only)')
w('node --experimental-strip-types $T/recluster.ts $T/clusters.json')
w('# 2. the data files')
w('$V $T/neighbours.py && $V $T/coverage.py')
w('# 3. the markdown')
w('$V $T/render_neighbours.py && $V $T/render_coverage.py')
w('```')
w('')
w('Nothing in the chain decodes an image except the final header read on the eight drawn covers,')
w('nothing touches the GPU, and nothing writes outside `research/v3/phase-3/embeddings/`.')
w('')
open(f'{OUT}/COVERAGE.md','w').write('\n'.join(L)+'\n')
print('wrote COVERAGE.md', len(L))
