import json, os
OUT='/Users/Flo/GitHub/palette/research/v3/phase-3/embeddings'
d=json.load(open(f'{OUT}/neighbours.json'))
L=[]
w=L.append
w('# Failure-class neighbourhoods')
w('')
w('**Files:** `NEIGHBOURS.md` (this) and `neighbours.json` (machine-readable, every field below plus')
w('the per-neighbour review batch ids).')
w('')
w('## What this is for')
w('')
w('Nine seed covers, one per named Phase 3 failure, each with its **k=12 nearest neighbours** by')
w('cosine on the canonical embedding arm. The point is to let a fix be tested on *many artworks of')
w('the same kind* instead of on the single cover that produced the complaint.')
w('')
w('## Method')
w('')
w(f"- **Arm:** `{d['arm']}` at 224 px — the canonical arm (decision `{d['armDecision']}`). No new")
w('  embedding was computed: every seed and every pool member already had a vector on disk.')
w(f"- **Metric:** {d['metric']}.")
w('- **Granularity:** artwork, not file. One vector per artwork — its largest rendition, by the same')
w('  rule the coverage set and the holdout freeze use (measured pixel area; ties prefer the')
w('  un-suffixed original, then the lexicographically smallest path). Renditions of one artwork')
w('  therefore cannot appear as each other’s neighbours.')
p=d['pool']
w(f"- **Pool (as briefed):** {p['what']} — **{p['size']} artworks** "
  f"({', '.join(f'{k} {v}' for k,v in sorted(p['bySource'].items()))}; "
  f"{', '.join(f'{k} {v}' for k,v in sorted(p['byCollection'].items()))}).")
w(f"  The holdout/quarantine filter removed **{p['excludedAsHoldoutOrQuarantine']}** artworks — {p['excludedNote']}.")
w(f"  {p['eval142NotInEmbeddedCorpus']} eval-142 entries are legacy `images/` covers that were never embedded and cannot enter any pool.")
w(f"- **Reviewed flag:** {d['reviewedFlag']['method']}. Source: `{d['reviewedFlag']['source']}`.")
cw=d['corpusWidePool']
w(f"- **Corpus-wide supplement ({cw['size']} artworks):** {cw['what']}")
w('')
w('## Headline: the briefed pool is too thin for this job')
w('')
w('| failure class | seed | k=12 cosine range | ≥ 0.6 | **unreviewed ≥ 0.6** | corpus-wide ≥ 0.6 | corpus-wide unreviewed ≥ 0.6 |')
w('|---|---|---|---|---|---|---|')
for s in d['seeds']:
    n=s['neighbours']; wd=s['corpusWideNeighbours']
    w(f"| {s['failureClass']} | `{s['seed']['stem'][:16]}…` | {n[0]['cosine']:.3f}–{n[-1]['cosine']:.3f} | {s['above0_6']} | **{s['unreviewedAbove0_6']}** | {s['corpusWideAbove0_6']} | {s['corpusWideUnreviewedAbove0_6']} |")
w('')
tot_u=sum(s['unreviewedAbove0_6'] for s in d['seeds'])
tot_uw=sum(s['corpusWideUnreviewedAbove0_6'] for s in d['seeds'])
w(f'Across all nine seeds the briefed pool supplies **{tot_u} unreviewed neighbours above cosine 0.6**;')
w(f'the whole corpus supplies **{tot_uw}**. Read that as two separate facts:')
w('')
w('1. **A 668-artwork pool is a 7% sample of the corpus, and it is too sparse to hold same-kind')
w('   company for an arbitrary cover.** Where a class does have a real neighbourhood, widening the')
w('   pool finds it (`…094a786a…`: 5 → 12 neighbours above 0.6). The corpus-wide table is the one')
w('   to draw a test set from.')
w('2. **Some of these classes are not neighbourhoods at all.** `label-logo`, `frame-letterbox`')
w('   (`9c44f2ac…`) and the degenerate `no-field` seed have nothing above 0.6 even corpus-wide.')
w('   These failures are compositional properties — a thin logo, a border, an absent field — and')
w('   DINOv2 similarity is dominated by subject and palette, not by that geometry. For those three,')
w('   nearest-neighbour retrieval is the wrong instrument, and the honest move is a *measured*')
w('   probe set (the frame and retreat fixtures already in `data/devloop/sets/` are exactly that)')
w('   rather than an embedding query.')
w('')
w('## Per-class neighbourhoods')
w('')
w('Each table is the seed’s k=12 in the briefed pool. `reviewed?` is over the whole warehouse —')
w('any batch, any record type — not only Phase 2 and Phase 3.')
w('')
cls_order=[]
for s in d['seeds']:
    if s['failureClass'] not in cls_order: cls_order.append(s['failureClass'])
for cls in cls_order:
    w(f'### {cls}')
    w('')
    for s in [x for x in d['seeds'] if x['failureClass']==cls]:
        sd=s['seed']
        w(f"#### seed `{sd['stem']}`")
        w('')
        w(f"`{sd['path']}` — {sd['wxh']}, tier {sd['tier']}, cluster {sd['cluster']}, "
          f"{'in the pool' if sd['inPool'] else '**not in the briefed pool** (a corpus cover outside coverage-set-1 / eval-142 / shard 15)'}, "
          f"{'reviewed in ' + ', '.join(f'`{b}`' for b in sd['reviewedIn']) if sd['everReviewed'] else 'never reviewed'}.")
        w('')
        w(f"Why this seed: {sd['why']}")
        w('')
        w('| # | cosine | id | path | WxH | cl | source | reviewed? |')
        w('|---|---|---|---|---|---|---|---|')
        for n in s['neighbours']:
            src=','.join(x.replace('coverage-set-1:','cs1-') for x in (n['poolSources'] or []))
            rev=', '.join(f"`{b}`" for b in n['reviewedIn']) if n['everReviewed'] else 'no'
            w(f"| {n['rank']} | {n['cosine']:.3f} | `{n['stem']}` | `{n['path']}` | {n['wxh']} | {n['cluster']} | {src} | {rev} |")
        w('')
        w('<details><summary>corpus-wide k=12 (supplement, beyond the briefed pool)</summary>')
        w('')
        w('| # | cosine | id | path | WxH | cl | reviewed? |')
        w('|---|---|---|---|---|---|---|')
        for n in s['corpusWideNeighbours']:
            rev=', '.join(f"`{b}`" for b in n['reviewedIn']) if n['everReviewed'] else 'no'
            w(f"| {n['rank']} | {n['cosine']:.3f} | `{n['stem']}` | `{n['path']}` | {n['wxh']} | {n['cluster']} | {rev} |")
        w('')
        w('</details>')
        w('')
w('## Seed provenance and the two judgement calls')
w('')
w('Four seeds were named in the task and resolve unambiguously. Five were not, and were chosen')
w('under a stated rule:')
w('')
w('**frame/letterbox.** `ground-test-1.jsonl` and `retreat-test-4.md` rank the 8-cover')
w('`data/devloop/sets/frame-probe.txt` fixture by two different measures, and they disagree.')
w('By the field literally named `thickness` the two thickest are `b4a18636…` (0.249) and')
w('`cc35f7f9…` (0.140); by pixel share, `retreat-test-4.md` names `9c44f2ac…` (0.478) and')
w('`7b51bde9…` (0.446) *in prose* as “the two thick-frame covers”. **The prose pair is used**,')
w('because it is the one the measurement doc itself calls out and because `ground-test-1.jsonl`')
w('independently corroborates it as frame-*shaped* (`9c44f2ac…` reach 0.999, enclosure 1.0),')
w('whereas the thickest-by-band cover `b4a18636…` has enclosure 0.0005 — a large flat band that')
w('encloses nothing. Both alternates are in the corpus with embeddings if the other reading is')
w('wanted: `music_artworks:b4a18636207b8de2cb0d9d4e9747bd71` (cluster 23) and')
w('`music_artworks:cc35f7f97c2c503a2812639457eae265` (cluster 23).')
w('')
w('**no-field/photographic.** All 18 covers in `data/devloop/sets/retreat-probe-2.txt` carry')
w('`accepted: 0` — no field component was accepted at all — with the unexplained remainder covering')
w('92–100% of the image. Three were taken, none of them already reviewed (6 of the 18 are: they are')
w('round-2 covers or the phase2 veto), one per structural sub-kind, and they happen to span three')
w('resolution tiers and three clusters: the maximally degenerate full-canvas case')
w('(`…0003e28f…`, remainderArea 1.0, no rejected attempts), a case with competing rejected')
w('attempts (`952266f2…`, remainderArea 0.956, enclosure 0.943), and the least degenerate')
w('(`…0013d322…`, remainderArea 0.925).')
w('')
w('## Caveats')
w('')
w('1. **Neighbour ≠ same failure.** Cosine proximity in DINOv2 space is visual similarity, not')
w('   shared failure mode. Nothing here has been checked by eye or by running an arm. A')
w('   neighbourhood is a *candidate* test set; it becomes evidence only once the fix is run on it.')
w('2. **Two seeds sit outside the briefed pool** (`9c44f2ac…`, `7b51bde9…`) and one class’s seeds')
w('   are mostly inside it. That asymmetry is a property of where the probe fixtures were drawn')
w('   from, not of the classes.')
w('3. **The near-duplicate census is a documented lower bound.** A neighbour listed as unreviewed')
w('   could still be a near-copy of a reviewed cover below cosine 0.95. This carries the same')
w('   caveat round 1 and round 2 carry.')
w('4. **`reviewed?` is deliberately broad.** It fires on SAM, perception and oracle batches as well')
w('   as on palette verdicts, so a cover marked reviewed has not necessarily had a *palette*')
w('   judged. `reviewedIn` in the JSON names the batches; check it before treating a cover as spent.')
w('')
w('## Reproducing this')
w('')
w('```')
w('cd /Users/Flo/GitHub/palette')
w('V=research/v3/oracle/embeddings/.venv/bin/python')
w('T=research/v3/phase-3/embeddings/tools')
w('# 1. recover the coverage-set clustering (writes tools/clusters.json, ~5 MB, ~2 min, CPU only)')
w('node --experimental-strip-types $T/recluster.ts $T/clusters.json')
w('# 2. the data files')
w('$V $T/neighbours.py && $V $T/coverage.py')
w('# 3. the markdown')
w('$V $T/render_neighbours.py && $V $T/render_coverage.py')
w('```')
w('')
w('Nothing in the chain decodes an image except the final header read on the eight drawn covers,')
w('nothing touches the GPU, and nothing writes outside `research/v3/phase-3/embeddings/`.')
w('')
open(f'{OUT}/NEIGHBOURS.md','w').write('\n'.join(L)+'\n')
print('wrote NEIGHBOURS.md', len(L), 'lines')
